### PR TITLE
iKalista.csproj

### PR DESCRIPTION
**Pull request by firas500**
can it work on elobuddy?

### CODE REVIEW

**Comment by blacky** [comment]
nty

**Comment by firas500** [comment]
what programe u use to make these scripts?

**Comment by firas500** [comment]
i really wanna know

**Comment by DZ191** [comment]
We use Paint.NET
You just imagine the script. Then you draw it in the program. Then you go to File -> Export -> L# Assembly.

When you get the prompt save it as <name>.lsharpassembly and then double click it to uplod to github and install it.

Hope it helped :)

**Comment by xcsoftforlsharp** [comment]
:stuck_out_tongue:

**Pull request closed without merging**
